### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by oztaser** [aligoren/ghostly-theme#1]
benimki  daha güzel sanki :smile: 

şu responsive menuyu hallederim bir ara :smiley:

**Comment by aligoren** [comment]
Olur çok sağol. Bir de şu alt kısımdaki footer var ya ölüm gibi. Ön sayfada alt kısma sabitleyemedim. Seninkini de geliştiriyorum dur bakalım :P

**Comment by oztaser** [comment]
#2

**Comment by aligoren** [comment]
@oztaser Şimdi fark eyledim de iki yazının ortasında kalıyormuş footer. Acaba sende de aynı durumda mı?

**Comment by oztaser** [comment]
tam anlamadım resim var mı? ben request içine koymuştum tam boyut bir resim

**Comment by oztaser** [comment]
hatta fullscreen bir resim atıyorum @aligoren 
![theme4](https://cloud.githubusercontent.com/assets/14043036/12413404/3aeb7496-be97-11e5-9fe0-2913797003b4.png)

**Comment by aligoren** [comment]
Anasayfada oluyor o aslında10:27, 19 Ocak 2016, "Adil ÖZTAŞER" <notifications@github.com>:hatta fullscreen bir resim atıyorum @aligoren   —Reply to this email directly or view it on GitHub.     Yandex.Mail mobil sürümünden gönderildi: http://m.ya.ru/ymail

**Comment by oztaser** [comment]
bende bir sıkıntı yok direk depoyu clonlayıp bir localde denesene

**Comment by aligoren** [comment]
Şöyle görünüyor bende :S

![dosya](https://cloud.githubusercontent.com/assets/4205423/12415093/55cd6674-bea2-11e5-9944-471ff9ac6adf.png)

**Comment by oztaser** [comment]
çok garip ya direk bu deponun clonu mu? bende gayet sağlıklı. varsa bir önbellek falan temizlesen?

**Comment by aligoren** [comment]
@oztaser temizledim hala o orta kısımda kalıyor yine :/ evet repodan clone

**Comment by oztaser** [comment]
akşam eve geçince onada bir bakıyım

**Comment by aligoren** [comment]
@oztaser olur çok sağol. uğraştırdım seni de :/

**Comment by oztaser** [comment]
görevimiz :+1:  @aligoren
